name: delivery_app
description: A modern delivery and logistics management application.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # UI
  cupertino_icons: ^1.0.6
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.9
  shimmer: ^3.0.0
  lottie: ^2.7.0
  cached_network_image: ^3.3.0

  # State Management
  provider: ^6.1.1

  # Network & API
  http: ^1.1.0
  dio: ^5.3.3
  connectivity_plus: ^5.0.1

  # Storage
  shared_preferences: ^2.2.2
  path_provider: ^2.1.1

  # Firebase
  firebase_core: ^2.24.0
  firebase_auth: ^4.15.0
  firebase_messaging: ^14.7.6
  cloud_firestore: ^4.13.3
  firebase_storage: ^11.5.3

  # Location & Maps
  google_maps_flutter: ^2.5.0
  location: ^5.0.3
  geolocator: ^10.1.0
  geocoding: ^2.1.1
  flutter_polyline_points: ^2.0.3 # Versión actualizada

  # QR Code
  qr_code_scanner_plus: ^2.0.10+1
  qr_flutter: ^4.1.0

  # Signature Capture
  signature: ^5.4.0

  # Date & Time
  intl: ^0.18.1

  # Utils
  url_launcher: ^6.2.1
  image_picker: ^1.0.4
  permission_handler: ^11.0.1
  flutter_local_notifications: ^16.2.0
  device_info_plus: ^9.1.0
  package_info_plus: ^4.2.0
  uuid: ^4.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.6

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/
    - assets/config/

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/app_icon.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/icons/app_icon_foreground.png"

flutter_native_splash:
  color: "#3D5AF1"
  image: assets/images/splash_logo.png
  android: true
  ios: true